/* src/pages/Success.js */
import React, { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "../styles/Success.css";
import { motion } from "framer-motion";
import jsPDF from "jspdf";
import { useToast } from "../components/ToastProvider";
import { CheckCircle } from "lucide-react";

const Success = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const toast = useToast();

  // ✅ booking object comes from Checkout or Dashboard
  const booking = useMemo(() => location.state || null, [location.state]);

  const [bookingId, setBookingId] = useState("");
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);


  useEffect(() => {
    // ✅ Always prefer booking.bookingId (from Checkout)
    const id =
      booking?.bookingId ||
      "EVT-" + Math.random().toString(36).slice(2, 7).toUpperCase();
    setBookingId(id);


  }, [booking]);

  const formatMoney = (value) => {
    const num = Number(value);
    if (!Number.isFinite(num)) return "—";
    if (num === 0) return "Free";
    return `$${num}`;
  };

  const safeText = (val, fallback = "—") =>
    val === null || val === undefined || val === "" ? fallback : String(val);

  const nowLabel = () =>
    new Date().toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });

  const handleCopyBookingId = async () => {
    try {
      await navigator.clipboard.writeText(bookingId);
      toast.success("Booking ID copied");
    } catch {
      // fallback
      try {
        const ta = document.createElement("textarea");
        ta.value = bookingId;
        document.body.appendChild(ta);
        ta.select();
        document.execCommand("copy");
        document.body.removeChild(ta);
        toast.success("Booking ID copied");
      } catch {
        toast.error("Copy failed. Please copy manually.");
      }
    }
  };

  const handleDownload = () => {
    setIsDownloading(true);

    setTimeout(() => {
      try {
        const doc = new jsPDF("p", "pt", "a4");

        // Header
        doc.setFont("helvetica", "bold");
        doc.setFontSize(20);
        doc.text("EVENTLY$", 40, 60);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.text("Ticket Receipt (Digital Pass)", 40, 82);

        doc.setDrawColor(200);
        doc.line(40, 98, 555, 98);

        // Booking details
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text("Booking ID", 40, 130);
        doc.setFont("helvetica", "normal");
        doc.text(safeText(bookingId), 160, 130);

        doc.setFont("helvetica", "bold");
        doc.text("Status", 40, 155);
        doc.setFont("helvetica", "normal");
        doc.text(safeText(booking?.status, "PAID"), 160, 155);

        doc.setFont("helvetica", "bold");
        doc.text("Generated", 40, 180);
        doc.setFont("helvetica", "normal");
        doc.text(nowLabel(), 160, 180);

        // Gold card
        doc.setDrawColor(240);
        doc.setFillColor(252, 203, 0);
        doc.roundedRect(40, 210, 515, 110, 12, 12, "F");

        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text(safeText(booking?.title, "Event Ticket"), 60, 245);

        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.text(`Date: ${safeText(booking?.date)}`, 60, 270);
        doc.text(`Location: ${safeText(booking?.location)}`, 60, 290);
        doc.text(`Tickets: ${safeText(booking?.qty, "1")}`, 60, 310);

        // Total
        doc.setTextColor(20);
        doc.setFont("helvetica", "bold");
        doc.text(`Total Paid: ${formatMoney(booking?.total ?? 0)}`, 360, 310);

        // Footer
        doc.setTextColor(80);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text(
          "Please bring this ticket (digital or printed) for check-in. ID may be required.",
          40,
          360
        );

        doc.setTextColor(120);
        doc.text("© Eventlys • Generated by Evently$", 40, 780);

        doc.save(`Ticket_${bookingId}.pdf`);

        setIsDownloading(false);
        setDownloaded(true);
        toast.success("Ticket downloaded");

        setTimeout(() => setDownloaded(false), 2500);
      } catch (err) {
        console.error(err);
        setIsDownloading(false);
        toast.error("Could not generate PDF. Try again.");
      }
    }, 1200);
  };

  // ✅ Guard if user refreshes Success and state is missing
  const missing = !booking?.title;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.35, ease: "easeOut" }}
    >
      <div className="success-wrapper animate-up">
        <div className="success-card">
          {/* optional perforation right (if you added the CSS earlier) */}
          <div className="ticket-perf-right" />

          <div className="success-icon"><CheckCircle size={48} /></div>
          <h2 style={{ fontFamily: "Cinzel", fontWeight: "bold" }}>
            Booking Confirmed!
          </h2>

          {/* Receipt summary */}
          <div style={{ marginTop: "10px", opacity: 0.92 }}>
            <p style={{ margin: "6px 0" }}>
              <strong>Event:</strong> {safeText(booking?.title)}
            </p>
            <p style={{ margin: "6px 0" }}>
              <strong>Date:</strong> {safeText(booking?.date)}
            </p>
            <p style={{ margin: "6px 0" }}>
              <strong>Location:</strong> {safeText(booking?.location)}
            </p>
            <p style={{ margin: "6px 0" }}>
              <strong>Tickets:</strong> {safeText(booking?.qty, "1")}
            </p>
            <p style={{ margin: "6px 0" }}>
              <strong>Total Paid:</strong> {formatMoney(booking?.total ?? 0)}
            </p>
          </div>

          <div className="booking-id-box">
            <h4>Your Booking ID</h4>

            <div className="booking-id-row">
              <p className="booking-id-text">{bookingId}</p>

              <button
                type="button"
                className="btn-copy-id"
                onClick={handleCopyBookingId}
                disabled={!bookingId}
              >
                Copy
              </button>
            </div>
          </div>

          <div className="download-container">
            <button
              className={`btn-download ${downloaded ? "success-gold" : ""}`}
              onClick={handleDownload}
              disabled={isDownloading}
              type="button"
            >
              {isDownloading ? (
                <span className="loader"></span>
              ) : downloaded ? (
                <><CheckCircle size={18} className="inline-block mr-2" style={{ verticalAlign: 'middle' }} /> Ticket Downloaded</>
              ) : (
                "Download PDF Ticket"
              )}
            </button>
          </div>

          {missing && (
            <p style={{ marginTop: "14px", color: "#666", fontSize: "0.9rem" }}>
              Receipt details were not found (page refreshed). Your booking ID is still valid.
            </p>
          )}

          <button
            className="btn-dashboard-return"
            onClick={() => navigate("/dashboard")}
            type="button"
          >
            Go to My Dashboard
          </button>

          <button
            className="btn-login-outline"
            style={{ marginTop: "10px" }}
            onClick={() => navigate("/events")}
            type="button"
          >
            Explore More Events
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export default Success;
